apiVersion: v1
kind: Service
metadata:
  name: fastapi-scraper
  labels:
    app: fastapi-scraper
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: fastapi-scraper
  selector:
    app: fastapi-scraper