apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-scraper-consumer
  labels:
    app: fastapi-scraper-consumer
spec:
  selector:
    matchLabels:
      app: fastapi-scraper-consumer
  template:
    metadata:
      labels:
        app: fastapi-scraper-consumer
    spec:
      containers:
        - name: hh-scraping
          image: praktika_leto-fastapi_scraper:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8000
          command: 
            - "export" 
          args:
            - "PYTHONPATH=$PYTHONPATH:$PWD"
          workingDir: /src
          command:
            - "python"
          args:
            - "-m"
            - "scraper.consumer"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-scraper-consumer-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-scraper-consumer
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
