apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi_app
spec:
  selector:
    matchLabels:
      project: hh-scraping-fastapi
  template:
    metadata:
      labels:
        project: hh-scraping-fastapi
    spec:
      containers:
        - name: hh-scraping-fastapi
          image: praktika_leto-fastapi:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80