apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-scraper
  labels:
    app: fastapi-scraper
spec:
  selector:
    matchLabels:
      app: fastapi-scraper
  template:
    metadata:
      labels:
        app: fastapi-scraper
    spec:
      containers:
        - name: hh-scraping
          image: praktika_leto-fastapi_scraper:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8000
          # command: ["echo"]
          # args: ["$pwd"]
          workingDir: /src
          command:
            - "uvicorn"
          args:
            - "scraper.app:app"
            - "--host=0.0.0.0"
            - "--port=8000"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-scraper-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-scraper
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
