apiVersion: v1
kind: Service
metadata:
  name: fastapi-oauth
  labels:
    app: fastapi-oauth
spec:
  type: ClusterIP
  ports:
    - port: 8800
      targetPort: 8800
      protocol: TCP
      name: fastapi-oauth
  selector:
    app: fastapi-oauth