apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastapi-oauth
  labels:
    app: fastapi-oauth
spec:
  selector:
    matchLabels:
      app: fastapi-oauth
  template:
    metadata:
      labels:
        app: fastapi-oauth
    spec:
      containers:
        - name: hh-scraping
          image: praktika_leto-fastapi_oauth:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8800
          workingDir: /src
          command:
            - "uvicorn"
          args:
            - "oauth.app:app"
            - "--host=0.0.0.0"
            - "--port=8800"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-oauth-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-oauth
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80