apiVersion : apps/v1
kind: Deployment
metadata:
  name: fastapi-oauth-consumer
  labels:
    app: fastapi-oauth-consumer
spec:
  selector:
    matchLabels:
      app: fastapi-oauth-consumer
  template:
    metadata:
      labels:
        app: fastapi-oauth-consumer
    spec:
      containers:
        - name: hh-scraping
          image: praktika_leto-fastapi_oauth:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8080
          command: 
            - "export" 
          args:
            - "PYTHONPATH=$PYTHONPATH:$PWD"
          workingDir: /src
          command:
            - "python"
          args:
            - "-m"
            - "oauth.consumer"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-oauth-consumer-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-oauth-consumer
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80