apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app  : nodejs_app
spec:
  selector:
    matchLabels:
      project: hh-scraping-nodejs
  template:
    metadata:
      labels:
        project: hh-scraping-nodejs
    spec:
      containers:
        - name: hh-scraping-nodejs
          image: praktika_leto-nodejs:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: env
          ports:
            - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80