apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app  : nodejs_app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app  : nodejs_app