apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-scraper
  labels:
    app: pg-scraper
spec:
  selector:
    matchLabels:
      app: pg-scraper
  template:
    metadata:
      labels:
        app: pg-scraper
    spec:
      containers:
        - name: pg-scraper
          image: postgres:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
              name: pg-scraper
          envFrom:
            - secretRef:
                name: scraper-pg.env

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pg-scraper-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pg-scraper
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80