apiVersion: v1
kind: Service
metadata:
  name: pg-oauth
  labels:
    app: pg-oauth
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pg-oauth
      protocol: TCP
      name: pg-oauth
  selector:
    app: pg-oauth