apiVersion: v1
kind: Service
metadata:
  name: pg-scraper
  labels:
    app: pg-scraper
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: pg-scraper
      protocol: TCP
      name: pg-scraper
  selector:
    app: pg-scraper