apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app: pg
spec:
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:14
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
              name: pg
          envFrom:
            - secretRef:
                name: env

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pg-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pg
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80