apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: rabbitmq
      protocol: TCP
      name: rabbitmq
  selector:
    app: rabbitmq