from python:3.12.4-slim

LABEL name="fastapi_scraper"

WORKDIR .
RUN mkdir /src

COPY ./src/backend/scraper/config/req.txt /src/scraper/req.txt
RUN python -m pip install -r ./src/scraper/req.txt

COPY ./src/backend/scraper /src/scraper/